### ISSUE TITLE
Inconsistent Scale Reading 

### ISSUE THREAD

**Issue by ChingPangggg** [AguaClara/Fluoride_Gravity#10]
![image](https://user-images.githubusercontent.com/35943545/45979617-97e8c880-c01d-11e8-948a-850b3f53db41.png)
We connected the balance to ProCoDA but the reading seems to be inconsistent as shown as the image above.

**Comment by ChingPangggg** [comment]
Hi @oliver-leung (admin access) can you install ProCoDA update on the sensor development computer for us?

**Comment by oliver-leung** [comment]
@ChingPangggg sure thing, I'll get it installed by tomorrow afternoon!

**Comment by oliver-leung** [comment]
@ChingPangggg The update has been installed, let me know if you run into any problems with it.

**Comment by ChingPangggg** [comment]
Changed to scoutpro balance, and reading was consistent
