### ISSUE TITLE
EPA credit for support of this project in reports and presentations

### ISSUE THREAD

**Issue by monroews** [AguaClara/Fluoride_Gravity#14]
The following statement must be included in reports and presentations that your teams generate. Please go back and add the first acknowledgement into any reports published 

between 02/01/2017 and now
This publication [article] was developed under Assistance Agreement No. SU-83695001 awarded by the U.S. Environmental Protection Agency to Cornell University.  It has not been formally reviewed by EPA.  The views expressed in this document are solely those of [name of recipient or names of authors] and do not necessarily reflect those of the Agency.  EPA does not endorse any products or commercial services mentioned in this publication.

**Comment by ChingPangggg** [comment]
Made edits to both Spring 2018 and Summer 2018 reports and presentations.
